blank_issues_enabled: false
contact_links:
  - name: Issue with the original Windows application (C#)
    url:  https://github.com/gitextensions/gitextensions/issues
    about: Problems that also happen in the original Git Extensions belong in its repository
